
#' import Open Clinica data
#'
#' Takes text files generated from Open Clinica and does some initial formatting saving them in an R format.
#'
#' @param txt Filename
#' @param path Filepath
#' @param dates A vector of column names to convert to dates
#' @param trialStub A string to filter unwanted files from the target folder
#' @param dbName The file name for the .Rdata file will all the data contained within it
#' @param delStub A string to remove off the data.frames if the names contain lots of unwanted duplication
#'
#' @details
#'
#' \code{import.openClinica} creates a data.frame from a comma delimited file. Any column with the word date and any column named in the date variable in it is formatted to a \code{\link{POSIXct}} date
#'
#' \code{}
#'
#' (path,trialStub,dbName,newFolder,delStub="")
#'
#'
#' @export import.openClinica
import.openClinica=function(txt,path,dates=NULL){


  # read trial.data from comma delimited text file
  if(substr(path,nchar(path),nchar(path))!="/"){
    path=paste0(path,"/")
  }
  trial.data=read.csv(paste0(path,txt),stringsAsFactors=FALSE)

  # Save all column names
  trial.data.names=names(trial.data)

  # Search for dates with the string "date" contained in their name
  dates2=trial.data.names[grep("date",names(trial.data))]
  if(!is.null(dates)){
    dates=unique(dates2,dates)
  } else {
    dates=dates2
  }

  # convert dates into posixct date-times (r date format)
  if(!is.null(dates)){
    for(i in dates){
      trial.data[i]=as.POSIXct(as.vector(t(trial.data[i])), tz = "", format="%d/%m/%Y %H:%M:%S",origin="1970-01-01")
    }
  }

  # Discard label values since R cannot cope with factors in an interilligent way
  # Transfer labels from name_label to name
  labels=trial.data.names[grep("label",names(trial.data))]
  for(label in labels){
    slab=sub("_label","",label)
    trial.data[slab]=trial.data[label]
    trial.data[label]=NULL
  }

  if("ssid" %in% trial.data.names){
    # rename ssid patid and bring to front of table
    trial.data$patid=trial.data$ssid
    trial.data$ssid=NULL
    trial.data=trial.data[,c("patid",setdiff(names(trial.data),"patid"))]
  }


  # Conservatively remove unwanted variable
  trial.data$item_trial.data_id=NULL
  trial.data$ssoid=NULL
  trial.data$oc_event_start_date=NULL
  trial.data$oc_event_end_date=NULL
  trial.data$event_status=NULL
  trial.data$event_location=NULL
  trial.data$subject_age_at_event=NULL
  trial.data$crf_status=NULL
  trial.data$interviewername=NULL
  trial.data$interviewdate=NULL
  trial.data$warehouse_insert_created_timestamp=NULL

  return(trial.data)
}

#' @rdname import.openClinica Runs import.openClinica on a folder and saves to an .Rdata file.
#' @export import.openClinica.batch
import.openClinica.batch = function(path,trialStub,dbName,newFolder,delStub=""){

  # find all files of interest
  files=list.files(paste0(path))
  # must contain trialStub
  files=files[grep(trialStub,files)]
  # must be text files
  files=files[grep(".txt",files)]

  print(files)
  # create folder for resulting Rdta file
  dir.create(newFolder)

  # run over each file
  trial.data=list()
    for(file in files){
      fname=gsub(".txt","",file)
      print(fname)
      if(delStub!=""){
        fname=gsub(delStub,"",fname)
      }

      trial.data[[fname]]=import.from.open.clinica(file,path,newFolder,dates=NULL)
      assign(fname,import.openClinica(file,path,newFolder,dates=NULL))
      #print(trial.data[[fname]])
    }

  if(substr(newFolder,nchar(newFolder),nchar(newFolder))!="/"){
    newFolder=paste0(newFolder,"/")
  }

  fnames=gsub(".txt","",files)
  if(delStub!=""){
    fnames=gsub(delStub,"",fnames)
  }

  db.list = c(fnames,"db.list")

  save(list=db.list,file=paste0(newFolder,dbName,".RData"))

}


#' Open Clinica as.POSIXct function
#'
#' This is a wrapper for \code{\link{as.POSIXct}} to make formating dates consistently and easily from Open clinica databases.
#'
#' @param data A date generated by Open Clinica
#'
#' @export OC_posIXct
OC.posIXct = function(data) {
  as.POSIXct(data, tz = "", format="%d/%m/%Y %H:%M:%S",origin="1970-01-01")
}



