#' Open Clinica as.POSIXct function
#'
#' This is a wrapper for \code{\link{as.POSIXct}} to make formating dates consistently and easily from Open clinica databases.
#'
#' @param data A date generated by Open Clinica
#'
#' @export OC_posIXct
OC_posIXct = function(data) {
  as.POSIXct(data, tz = "", format="%d/%m/%Y %H:%M:%S",origin="1970-01-01")
}
